project: 
  type: book

book:
  title: "An example thesis"
  author: "Cosmo Cougar"
  date: "2022"
  chapters:
    - index.qmd
    - 02_more.qmd
    - 03_articles.qmd
    - 04_conclusions.qmd
  references: 10_references.qmd
  appendices: 
    - 11_requirements.qmd
    - 12_etd.qmd
  abstract: |
   The abstract is summary of the work with emphasis on the findings of the study. 
   It is not intended to be an *introduction* to the research. Instead, it should 
   concisely state the problem addressed, the methods developed and used, and 
   the results obtained. It must be single spaced and no more than one page in 
   length. It must use the same font and font size as the rest of the work. 
   The abstract precedes the acknowledgment page and the body of the work.

# On the custom title page, use the same title, but format as you like
customtitle: |
  Exceptional Engineering 
  Research
  that Has Taken Too Long
# Layout options are simple/fancy, oneside/twoside, and masters/phd.
# Leave options blank for defaults.
# Defaults are simple for document style, and masters for degree type.
layout: fancy, oneside, masters
# If your degree is not a PhD or MS, then you can overwrite the degree using 
# the \degree command: \degree{Bachelors of Science}
# degree: Bachelors of Science with University Honors
department: Civil and Construction Engineering
# list your chair and any other members of your committee
chair: Norman D. Smith
committee:
  - Mary Q. Scott
  - Steven R. Jones
  - Anna B. Hanna
# Include any keywords you would like for your thesis/dissertation
keywords: 
  - awesome stuff
  - engineering
acknowledgments: | 
  Students should acknowledge funding sources. They may also use the acknowledgment page to express appreciation for the committee members, friends or family who provided support or aided the research, writing or technical aspects of the thesis/dissertation. Acknowledgments should be simple and in good taste.

csl: apa.csl
bibliography: references.bib
format:
  html:
    theme:
      - cosmo
  byu-thesis-pdf:
    keep-tex: true
    highlight-style: arrow